<?php

function groceries_menu() {
  $items = array();
  $items['my_groceries'] = array(
    'title' => 'My Groceries',
    'page callback' => 'all_groceries',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function grocery_list() {
  $groceries_array = array(
    'Eggs' => array(
      'price' => 2.50,
      'quantity' => 2,
    ),
    'Milk' => array(
      'price' => 3.99,
      'quantity' => 1,
    ),
    'Bread' => array(
      'price' => 1.99,
      'quantity' => 2,
    ),
  );
  return $groceries_array;
}

function item_total($price, $quantity) {
  return $price * $quantity;
}

function total_price() {
  $groceries_array = grocery_list();
  $total = 0;
  foreach($groceries_array as $grocery_item => $grocery_item_value) {
    $total = $total + $grocery_item_value['price'] * $grocery_item_value['quantity'];
  };
  return $total;
}

function all_groceries() {
  $display = '';
  $groceries_array = grocery_list();
  $total = total_price();
  foreach($groceries_array as $grocery_item => $grocery_item_value) {
    $display = $display . "<h3>" . $grocery_item . "</h3><ul>";
    foreach($grocery_item_value as $grocery_info_key => $grocery_info_value) {
      $display = $display . "<li>" . $grocery_info_key . ": " . $grocery_info_value . "</li>";
    };
    $display = $display . "<li>Total Price: $" . item_total($grocery_item_value['price'], $grocery_item_value['quantity']) . "</li></ul>";
  };
  $display = $display . '<p>Total Cost: $' . $total . '</p>';
  return $display;
}
