<?php

function cards_menu(){
  $friends = array("Alex", "Julia", "Emily");
  foreach($friends as $friend){
    $items['cards/' . $friend] = array(
      'title' => $friend,
      'page callback' => 'cards_generator',
      'page arguments' => array(1),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
  };
  return $items;
}

function cards_generator($args){
  $friend = $args;
  return "<h3>Hey, " . $friend . "! Hope all is well!</h3>";
}
