<?php

function cards_menu(){
  $friends = array("Gunther", "Frank", "Chad");
  foreach($friends as $friend){
    $items['cards/' . $friend] = array(
      'title' => $friend,
      'page callback' => 'cards_generator',
      'page arguments' => array(1),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
  };
  return $items;
}

function cards_generator($args){
  $friend = $args;
  return "<p>Hey " . $friend . " miss you</p>";
}
