<?php

function pet_menu(){
  $items = array();
  $items['my_pets'] = array(
          'title' => 'My Favorite Pets',
          'page callback' => 'display_pet',
          'access callback' => TRUE,
          'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function display_pet(){
  $image = drupal_get_path('module', 'pet') . '/dinosaur.jpg';
  return "<a href='http://www.livescience.com/3945-history-dinosaurs.html' target='_blank'>Dino Info</a>
    <image src=$image>";
}
