<?php

function ajax_link_menu(){
  $items = array();

  $items['ajax-test'] = array(
      'title' => 'Check the current time using Ajax!',
      'type' => MENU_NORMAL_ITEM, //type of menu item
      'page callback' => 'ajax_link_page',//references function
      'access arguments' => array('access content'),
  );
  $items['my-ajax-test/%'] = array(
      'title' => 'Ajax Test Callback',
      'type' => MENU_CALLBACK,
      'page callback' => 'ajax_link_callback',
      'page arguments' => array(1),
      'access arguments' => array('access content'),
  );
  return $items;
}

//callback function that displays a simple Ajax powered link
function ajax_link_page(){
  return array(
    '#type' => 'link',
    '#title' => t('Ajax Link'),
    '#href' => 'my-ajax-test/nojs',
    '#prefix' => '<div id="ajax-link">',
    '#suffix' => '</div><div id="ajax-display"></div>',
    '#ajax' => array( //Use Ajax, to make 'nojs'be 'js'
        'effect' => 'fade',
    ),
  );
}

//pass $ajax variable in which comes from page arguments array(1)
function ajax_link_callback($ajax){
  $time = t('The current time is: !time', array('!time' => date('Y-m-d H:i:s')));

  if($ajax == 'ajax'){
    $commands = array();

    //AJAX COMMAND TO REPLACE THE #ajax-display ELEMENT WITH THE CURRENT TIME
    $commands[] = ajax_command_replace('#ajax-display', "<div id='ajax-display'>" . $time . "</div>");

    //ADD A VISUAL CHANGE MARKER TO THE #ajax-display ELEMENT
    $commands[] = ajax_command_changed('#ajax-display');

    //CALLS OUR JQUERY PLUGIN CALLED 'ajax_link'
    $commands[] = ajax_command_invoke(NULL, "ajax_link");

    ajax_deliver(array('#type' => 'ajax', '#commands' => $commands));
  }
  else {
    return array(
      '#markup' => $time,
    );
  }
}
