<?php

function shift_cipher_menu(){
  $items['shift_cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
  );
  $items['shift_cipher_success_page'] = array(
        'title' => 'Shift Cipher Success Page',
        'page callback' => 'shift_cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
  );
  return $items;
}

function shift_cipher_form(){
  $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#description' => 'Enter a numerical shift value',
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
  );
  $form['direction'] = array(
        '#title' => 'Direction',
        '#description' => 'Enter Left or Right',
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
  );
  $form['phrase'] = array(
        '#title' => 'Phrase',
        '#description' => 'Enter the phrase you would like to code',
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_phrase'),
        '#required' => TRUE,
  );
  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Submit',
  );
  return $form;
}

function element_validate_direction($element){
  $input_direction = strtolower($element['#value']);
  $values = array('left', 'right');

  if(!in_array($input_direction, $values)){
    form_error($element, t("Please enter either 'Left' or 'Right'"));
  }
}

function element_validate_phrase($element){
  $input_phrase = strtolower($element['#value']);

  if (!preg_match("/^[a-zA-Z\ .'s]*$/", $input_phrase)) {
    form_error($element, t('You must enter letters only!'));
  }
}

function shift_cipher_form_submit($form, &$form_state){
  $input_shift_value = $form_state['values']['shift_value'];
  $input_direction = $form_state['values']['direction'];
  $input_phrase = $form_state['values']['phrase'];
  $_SESSION['phrase'] = $input_phrase;
  $output = '';

  if($input_direction === 'left'){
    $input_shift_value = 26 - $input_shift_value;
  }

  $input_phrase = str_split(strtolower($input_phrase));
  $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',     'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');


    foreach($input_phrase as $letter){ //loop through each letter in phrase
      if(in_array($letter, $alphabet)){ //assures the letter is in alpha array
        $key = array_search($letter, $alphabet); //letters are indexed
        $to_shift = ($key + $input_shift_value) % 26; //modulus operator
        $output .= $alphabet[$to_shift];

    } else{
      $output .= $letter;
    }
  }

  $original_phrase = $_SESSION['phrase'];
  $_SESSION['translated_phrase'] = $output;
  $form_state['redirect'] = 'shift_cipher_success_page';
}

function shift_cipher_success(){
  $original_phrase = $_SESSION['phrase'];
  // var_dump($_SESSION['translated_phrase']);
  return '<h2>Your original message: </h2>' . $original_phrase .
         '<h2>Encrypted phrase: </h2>' . $_SESSION['translated_phrase'] . '<br>' .
         '<img src=http://i.makeagif.com/media/1-18-2014/ESeo4v.gif>';

}
