<?php

function shift_cipher_menu(){
  $items['shift_cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
  );
  $items['shift_cipher_success_page'] = array(
        'title' => 'Shift Cipher Success Page',
        'page callback' => 'shift_cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
  );
  return $items;
}

function shift_cipher_form(){
  $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#description' => 'Enter a shift value',
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
  );
  $form['direction'] = array(
        '#title' => 'Direction',
        '#description' => 'Enter Left or Right',
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
  );
  $form['phrase'] = array(
        '#title' => 'Phrase',
        '#description' => 'Enter the phrase you would like to code',
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_phrase'),
        '#required' => TRUE,
  );
  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Submit',
  );
  return $form;
}

function element_validate_direction($element){
  $input_direction = strtolower($element['#value']);
  $values = array('left', 'right');

  if(!in_array($input_direction, $values)){
    form_error($element, t("Please enter either 'Left' or 'Right'"));
  }
}

function element_validate_phrase($element){
  $input_phrase = $element['#value'];

  if (!preg_match("/^[a-zA-Z\ .'s]*$/", $input_phrase)) {
    form_error($element, t('You must enter letters only!'));
  }
}

function shift_cipher_form_submit(){
  $form_state['redirect'] = 'shift_cipher_success_page';
}
function shift_cipher_success(){

}
