<?php

function dna_helix_menu(){
  $items['dna_helix'] = array(
    'title' => 'DNA Helix',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dna_helix_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['dna_helix_success_page'] = array(
    'title' => 'DNA Helix Success',
    'page callback' => 'dna_helix_results',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function dna_helix_form(){
  $form['input'] = array(
      '#title' => 'Helix',
      '#description' => 'Enter the first sequence of elements in your DNA',
      '#type' => 'textfield',
      '#element_validate' => array('element_validate_helix'),
      '#required' => TRUE,
  );
  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Submit',
  );
  return $form;
}

function element_validate_helix($element){
  $user_input = str_split(strtoupper($element['#value']));
  $nucleotides = array('A', 'T', 'C', 'G');

  foreach($user_input as $letter){
    if(!in_array($letter, $nucleotides)){
      form_error($element, t('The agents are getting suspicious, please enter only A, T, C, G' . '<img src=http://www.panicmanual.com/wp-content/uploads/2010/08/xfiles.jpg>'));
    }
  }
}

function make_dna($input){
  // $input = $form_state['values']['input'];
  $split_input = str_split(strtoupper($input));
  $_SESSION['input'] = $input;
  $output = '';

  foreach($split_input as $letter){
    if($letter === 'T'){
      $output .= 'A';
    } elseif ($letter === 'A'){
      $output .= 'T';
    }elseif($letter === 'C'){
      $output .= 'G';
    }elseif($letter === 'G'){
      $output .= 'C';
    }
  }
  return $output;

}

function dna_helix_form_submit($form, &$form_state){
  $input = $form_state['values']['input'];
  $output = make_dna($input);
  $_SESSION['user_input'] = strtoupper($input);
  $_SESSION['completed_dna'] = $output;
  $form_state['redirect'] = 'dna_helix_success_page';
}

function dna_helix_results(){
  $original_phrase = $_SESSION['user_input'];
  $full_dna = $_SESSION['completed_dna'];
  return '<h3>Your first set of helix:</h3>' . $original_phrase .
         '<h3>Your second set of helix:</h3>' . $full_dna .
         '<h3>Full DNA:</h3>' . $original_phrase . $full_dna .
         '<img src=http://45.media.tumblr.com/60545689ca8603898cf7517db24e4531/tumblr_ntd4pxhMUk1rnfdtuo1_500.gif>';
}
